---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: my-cert
spec:
  secretStoreRef:
    kind: SecretStore
    name: staging
  target:
    creationPolicy: Owner
  data:
  - secretKey: cert.crt
    remoteRef:
      key: my-cert
      property: cert.crt
  - secretKey: cert.key
    remoteRef:
      key: my-cert
      property: cert.key
