---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: my-env-config
spec:
  secretStoreRef:
    kind: SecretStore
    name: staging
  target:
    creationPolicy: Owner
  data:
  - secretKey: MY_ENV_VAR1
    remoteRef:
      key: my-cert
      property: MY_ENV_VAR1
  - secretKey: MY_ENV_VAR2
    remoteRef:
      key: my-cert
      property: MY_ENV_VAR2
